collective: captainfact_io
tiers:
  - tiers: '*'
    labels: ['backer']
    message: 'Hey <link>, thanks for supporting us on Open Collective. We'll give a special attention to this issue!'
invitation: |
  Hey <author> :wave:,

  Thank you for opening an issue. We will get back to you as
  soon as we can. Also, check out our Open Collective and consider
  backing us - every little helps!

  <link>
  
  PS.: We also offer bounties for some issues. Please tell us if you want to boost this issue with one! *See [bounty policy](https://github.com/CaptainFact/captain-fact/issues/54)*
  
