collective: captainfact_io
tiers:
  - tiers: "*"
    labels: ["backer"]
    message: "Hey <author> , thanks for supporting us on Open Collective :heart::heart::heart: We'll give a special attention to this issue!"
invitation: |
  Hey <author> :wave:,

  Thank you for opening an issue. We will get back to you as soon as we can.
  Also, check out our [Open Collective](https://opencollective.com/captainfact_io) and consider backing us - every little helps!

  :gift_heart: We also offer [bounties](https://github.com/CaptainFact/captain-fact/issues/54) for some issues, please tell us if you want to boost this issue with one!
